# Generated by Django 4.2.20 on 2025-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250414_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('chưa sử dụng', 'chưa sử dụng'), ('đã sử dụng', 'đã sử dụng')], max_length=50, null=True)),
                ('sub_status', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(choices=[('f1mail', 'f1mail'), ('đồng văn', 'đồng văn')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_provided', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRegProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('create_by', models.CharField(max_length=255)),
                ('use_at', models.CharField(max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status_account', models.CharField(choices=[('VERIFED', 'VERIFED'), ('MAIL LỖI', 'MAIL LỖI'), ('REG ACC LỖI', 'REG ACC LỖI'), ('SAI MẬT KHẨU', 'SAI MẬT KHẨU')], max_length=50)),
                ('sold_status', models.BooleanField(default=False)),
                ('supplier', models.CharField(choices=[('VIỆT', 'VIỆT'), ('QUÂN', 'QUÂN'), ('HOÀ', 'HOÀ')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status_account', models.CharField(choices=[('VERIFED', 'VERIFED'), ('MAIL LỖI', 'MAIL LỖI'), ('REG ACC LỖI', 'REG ACC LỖI'), ('SAI MẬT KHẨU', 'SAI MẬT KHẨU')], max_length=50)),
                ('check_detail', models.DateTimeField(null=True)),
                ('sold_status', models.BooleanField(default=False)),
                ('update_phone_day', models.DateTimeField(null=True)),
                ('supplier', models.CharField(choices=[('VIỆT', 'VIỆT'), ('QUÂN', 'QUÂN'), ('HOÀ', 'HOÀ')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.CharField(max_length=100, null=True)),
                ('total_accounts', models.IntegerField(default=0)),
                ('created_textnow_emails', models.TextField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
