# Generated by Django 4.2.20 on 2025-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_email_passwordregproduct_textfree_textnow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
