# Generated by Django 4.2.20 on 2025-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_role_useractivity_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
