# Generated by Django 4.2.20 on 2025-04-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useractivity_device_info_useractivity_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
