# Generated by Django 4.2.20 on 2025-04-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_useractivity_device_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='last_activity',
        ),
    ]
