# Generated by Django 4.2.20 on 2025-04-28 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_useractivity_device_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTextNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('password_TF', models.CharField(blank=True, max_length=255, null=True)),
                ('status_account_TN', models.CharField(default='chưa tạo acc', max_length=50)),
                ('status_account_TF', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_textnow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='PasswordRegProduct',
        ),
        migrations.DeleteModel(
            name='TextFree',
        ),
        migrations.DeleteModel(
            name='TextNow',
        ),
        migrations.DeleteModel(
            name='WorkSession',
        ),
    ]
