# Generated by Django 4.2.20 on 2025-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_employeetextnow_delete_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetextnow',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeetextnow',
            name='full_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetextnow',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetextnow',
            name='sold_status_TF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeetextnow',
            name='sold_status_TN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeetextnow',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
